### ISSUE TITLE
"blind inhibitor"

### ISSUE THREAD

**Issue by yum234** [grabz-dev/CW3-ERSKCCUFO#10]
Inhibitor which became visible and effective if player open several (for instance 3) Shield Keys.

**Comment by yum234** [comment]
One more variant: 
A) Simple case. We have 2 shield keys with number 1 and 2. MapMaker place on map 2 semi-visible (non-active) inhibitors with numbers 12 and 21. If player (when play a map) will get at first shield key 1 and then 2 will be activated Inhibitor with number 12. If shield key 2 and then 1, - Inhibitor with number 21. 
B) Complicated case for big map. If we have 3 shield keys it will be 6 variants of Inhibitors with numbers 123, 132, 213, 231, 312 and 321.

**Comment by yum234** [comment]
Before activation any of Inhibitors on the map can't be destroyed.

**Comment by kajacx** [comment]
Done,
A generic solution is in template: Any number of keys possible (1,2,3,4,...), also a single Inhibitor can have multiple combinations (for example: with 4 keys, have 4 inhibitors, and only the last key will determine which inhibitor will spawn - however mapmaker needs to set 6 combinations in each inhibitor by hand).
In template are 3 keys and 3 inhibitors, each have 2 combinations, but in general, any inhibitor can have any number of combinations, they don't have to have the same amount.
