### ISSUE TITLE
Flip-emitter and clever UFO

### ISSUE THREAD

**Issue by yum234** [grabz-dev/CW3-ERSKCCUFO#13]
1. Introduce in template one flip-creeperemitter which under anti-creeper can flip into anti-creeper emitter and vice versa
2. introduce one more type of UFO which can abduct any player's anti-creeper emitter (including after flipping of flip-creeperemitter).

**Comment by kajacx** [comment]
Done, can you check if it works properly? I tested it for a little bit, but it is always possible I missed something.
