### ISSUE TITLE
Limited range of UFO

### ISSUE THREAD

**Issue by yum234** [grabz-dev/CW3-ERSKCCUFO#4]
Will be good additional UFO setting: range of attack (9999 or xxx) - the same as in case of RainMakers.

**Comment by yum234** [comment]
Will be good additional UFO setting: range of attack (9999 or xxx) - the same as in case of RainMakers.

**Comment by yum234** [comment]
If possible better to make boundary of range zone not so "BOLD", please.

**Comment by kajacx** [comment]
OK I changed the image so it is a simple line, however 1px width looked really wierd, so I tried 1.5 and it is passable, I don't think it can be any less "bold" without cutting the ring into multiple images.
+ as bonus: hovering over UFO or UFO base will not show lines to UFO base or created UFOs.
